### PR TITLE
Don't embed streams in "nodeServices"

### PR DESCRIPTION
**Pull request by Raytar**
Embedding will not work when there are multiple quorum calls that use streams.

### CODE REVIEW

**Comment by meling** [comment]
Yep. That's my bad; didn't test it with multiple multicast/stream methods. Could you add another multicast method, e.g. `WriteMulticast()`, to the `zorums.proto` file as a "test case"?

**Comment by Raytar** [comment]
Done.

**Comment by Raytar** [comment]
Fixed a typo.

**Comment by meling** [comment]
LGMT

**Pull request merged**
